config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :pirate_ships do
    resources :bookings
  end

  get "/dashboard", to: "pages#dashboard", as: "dashboard"
  get "/map", to: "pages#map", as: "map"
  post "/accept", to: "pages#accept", as: "accept_booking"
  post "/reject", to: "pages#reject", as: "reject_booking"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  attr_accessor :password

  belongs_to :pirate_ship
  belongs_to :user

  validates :status, :start_date, :end_date, presence: true
end

app/models/pirate_ship.rb
class PirateShip < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  has_many_attached :pictures

  geocoded_by :port
  after_validation :geocode, if: :will_save_change_to_port?

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pirate_ships, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :rented_ships, through: :bookings, source: :pirate_ship

  validates :email, format: { with: /\A.*@.*\..*\z/ }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  def after_sign_in_path_for(resource)
    pirate_ships_path
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include Pundit
  before_action :find_pirate_ship, only: [:new, :create]
  after_action :verify_authorized, except: [:new, :create, :edit, :show]

  def show
    @booking = Booking.find(params[:id])

  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.pirate_ship = @pirate_ship
    @booking.status = "pending"
    @booking.user = current_user
    if @booking.save
      redirect_to pirate_ship_booking_path(@pirate_ship.id, @booking)
    else
      render :new
    end
  end

private

  def booking_params
    params.require(:booking).permit(:status, :start_date, :end_date, :user_id, :pirate_ship_id)
  end

  def find_pirate_ship
    @pirate_ship = PirateShip.find(params[:pirate_ship_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:home]
  include Pundit
  def home
  end

  def dashboard
    @user = current_user
    @name = @user.name || "you incog'ito matey"
    @pending_bookings = @user.bookings.select { |booking| booking.status == "pending" }
    @confirmed_bookings = @user.bookings.select { |booking| booking.status == "confirmed" }
    @owned_ships = @user.pirate_ships
    @pending_requests = Booking.where(status: "pending").select { |booking| booking.pirate_ship.user_id == @user.id}
    @confirmed_requests = Booking.where(status: "confirmed").select { |booking| booking.pirate_ship.user_id == @user.id}
    @rejected_requests = Booking.where(status: "rejected").select { |booking| booking.pirate_ship.user_id == @user.id}
    @markers = @owned_ships.geocoded.map do |pirate_ship|
      {
        lat: pirate_ship.latitude,
        lng: pirate_ship.longitude,
        info_window: render_to_string(partial: "info_window", locals: { pirate_ship: pirate_ship }),
        image_url: helpers.asset_url('harbor.svg')
      }
    end
  end

  def accept
    booking = Booking.find(params[:id])
    booking.status = "accepted"
    booking.save
    redirect_to dashboard_path
  end

  def reject
    booking = Booking.find(params[:id])
    booking.status = "rejected"
    booking.save
    redirect_to dashboard_path
  end

  def map
    @pirate_ships = PirateShip.all
    @markers = @pirate_ships.geocoded.map do |pirate_ship|
      {
        lat: pirate_ship.latitude,
        lng: pirate_ship.longitude,
        info_window: render_to_string(partial: "info_window", locals: { pirate_ship: pirate_ship }),
        image_url: helpers.asset_url('harbor.svg')
      }
    end
  end

  private

  def pages_params
    params.permit(:id)
  end
end

app/controllers/pirate_ships_controller.rb
class PirateShipsController < ApplicationController
  include Pundit
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_pirate_ship, only: [:show, :edit, :update]
  after_action :verify_authorized, except: [:index, :new, :create, :edit, :show, :update]

  def index
    @pirate_ships = policy_scope(PirateShip).order(created_at: :desc)
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query OR port ILIKE :query"
      @pirate_ships = PirateShip.where(sql_query, query: "%#{params[:query]}%")
    else
      @pirate_ships = PirateShip.all
    end
  end

  def show
    @markers = [{
      lat: @pirate_ship.latitude,
      lng: @pirate_ship.longitude,
      info_window: render_to_string(partial: "info_window", locals: { pirate_ship: @pirate_ship }),
      image_url: helpers.asset_url('harbor.svg')
      }]
  end

  def new
    @pirate_ship = PirateShip.new
  end

  def create
    @pirate_ship = PirateShip.new(pirate_ship_params)
    @pirate_ship.user = current_user
    if @pirate_ship.save
      redirect_to pirate_ship_path(@pirate_ship)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @pirate_ship.update(pirate_ship_params)

    redirect_to pirate_ships_path(@pirate_ship)
  end

  private

  def set_pirate_ship
    @pirate_ship = PirateShip.find(params[:id])
  end


  def pirate_ship_params
    params.require(:pirate_ship).permit(:name, :description, :ship_type, :capacity, :parrot_friendlyness,
                                        :number_of_canons, :port, pictures: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class='booking-form'>
  <div class="container py-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="booking-form">
          <h1>Select dates for: </h1>
          <h2><b><%=@pirate_ship.name%></b></h2>
          <% @pirate_ship.pictures.each do |picture| %>
              <%= cl_image_tag picture.key, alt: @pirate_ship.name, :class => "ship-page-image"%>
            <% end %>
          <%= simple_form_for [@pirate_ship, @booking] do |f| %>
          <%=f.input :start_date, as: :date, html5: true%>
          <%=f.input :end_date, as: :date, html5: true%>
          <%=f.button :submit, "Confirm_booking", class: "select-date-button"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/bookings/show.html.erb
<div class='booking-confirmation'>
  <% if @booking.status.downcase == "confirmerd"%>
    <h3 class="alert alert-success" role="alert"><%=@booking.status%><h3>
  <% elsif @booking.status.downcase == "pending"%>
    <h3 class="alert alert-primary" role="alert"><%=@booking.status%><h3>
  <% else%>
    <h3 class="alert alert-danger" role="alert"><%=@booking.status%><h3>
  <% end %>

  <% if @booking.status.downcase == "confirmerd"%> 
  <h1>All aboard !</h1> 
  <% end %>
    
  <h1>Ahoy ! this is ye booking for: <b><%=link_to @booking.pirate_ship.name, pirate_ship_path(@booking.pirate_ship)%></b></h1>

  <div>
    <h3>Start date: <%=@booking.start_date%></h3>
    <h3>Return date: <%=@booking.end_date%></h3>
  </div>  


  <div>
    <h3>Ye will be meeting <b><%=@booking.pirate_ship.user.name%></b> <%=image_tag @booking.pirate_ship.user.avatar_url, alt:@booking.pirate_ship.user.name, class: 'avatar-larger' %></h3>
    <h3>Weighing anchor at: <b><%=@booking.pirate_ship.port%></b>
  </div>


  <%=link_to "Back to Dashboard", dashboard_path, class: "back-dashboard-button"%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TORTUGABay</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel= "stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  </head>

  <body>
    <% unless current_page?(root_path) %>
      <%= render 'shared/navbar' %>
    <div class="container">
    <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    <% unless current_page? root_path %>
    </div>
    <% end %>

  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="row wrapper">
  <div class="col col-md-6 col-12">
    <div class="dashboard_card welcome d-flex align-items-center">
      <%= image_tag (current_user.avatar_url || 'pirate_skull.jpg'), class: "welcome_avatar" %>
      <div>
        <span>Welcome to yer dashboa'd</span>
        <h3 class="font-weight-bold"><%= current_user.name %></h3>
      </div>
    </div>
    <% if @pending_bookings.size > 0 %>
      <div class="dashboard_card">
        <div class="header renting">Ships yee requested to sail</div>
        <% if @pending_bookings.empty? %>
          <div class="ship_text d-flex flex-column m-2 ml-3">
            You have no pending bookings
          </div>
        <% else %>
          <% @pending_bookings.each do |booking| %>
            <div class="ship_card">
              <div class="d-flex flex-column m-2 ml-3">
                <span class="ship_text"><%= link_to booking.pirate_ship.name, pirate_ship_booking_path(booking.pirate_ship.id, booking) %></span>
                <span class="text-muted"><%= booking.start_date %> / <%= booking.end_date %></span>
              </div>
              <% unless @pending_bookings.last == booking %>
                <hr>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <% if @confirmed_bookings.size > 0 %>
      <div class="dashboard_card">
        <div class="header renting">Ships yee will sail</div>
        <% @confirmed_bookings.each do |booking| %>
          <div class="ship_card">
            <div class="d-flex flex-column m-2 ml-3">
              <span class="ship_text"><%= link_to booking.pirate_ship.name, pirate_ship_booking_path(booking.pirate_ship.id, booking) %></span>
              <span class="text-muted"><%= booking.start_date %> / <%= booking.end_date %></span>
            </div>
            <% unless @confirmed_bookings.last == booking %>
              <hr>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>

    <% if @pending_requests.size > 0 %>
      <div class="dashboard_card">
        <div class="header owned">This poor fella wants to give ya dubloons</div>
        <% @pending_requests.each do |booking| %>
          <div class="ship_card">
          <div class="d-flex align-items-center justify-content-between">
            <div class="d-flex flex-column m-2 ml-3">
              <span class="ship_text"><%= link_to booking.pirate_ship.name, pirate_ship_booking_path(booking.pirate_ship.id, booking) %></span>
              <span class="text-muted"><%= booking.start_date %> / <%= booking.end_date %></span>
            </div>
            <div class="d-flex">
              <%= button_to accept_booking_path, method: :post, params: { id: booking.id }, class: "button button-accept mr-3" do %>
                <i class="fas fa-khanda"></i>
              <% end %>
              <%= button_to reject_booking_path, method: :post, params: { id: booking.id }, class: "button button-reject mr-3" do %>
                <i class="fas fa-skull-crossbones"></i>
              <% end %>
            </div>
          </div>
            <% unless @pending_requests.last == booking %>
              <hr>
            <% end %>
          </div>
        <% end %>
    </div>
    <% end %>

    <% if @confirmed_requests.size > 0 %>
      <div class="dashboard_card">
        <div class="header owned">All the poor basta'ds who rented a ship</div>
        <% @confirmed_requests.each do |booking| %>
          <div class="ship_card">
            <div class="d-flex flex-column m-2 ml-3">
              <span class="ship_text"><%= link_to booking.pirate_ship.name, pirate_ship_booking_path(booking.pirate_ship.id, booking) %></span>
              <span class="text-muted"><%= booking.start_date %> / <%= booking.end_date %></span>
            </div>
            <% unless @confirmed_requests.last == booking %>
              <hr>
            <% end %>
          </div>
        <% end %>
    </div>
    <% end %>

    <% if @rejected_requests.size > 0 %>
      <div class="dashboard_card">
        <div class="header owned">All the little pirate dreams ya shredded</div>
        <% @rejected_requests.each do |booking| %>
          <div class="ship_card">
            <div class="d-flex flex-column m-2 ml-3">
              <span class="ship_text"><%= link_to booking.pirate_ship.name, pirate_ship_booking_path(booking.pirate_ship.id, booking) %></span>
              <span class="text-muted"><%= booking.start_date %> / <%= booking.end_date %></span>
            </div>
            <% unless @rejected_requests.last == booking %>
              <hr>
            <% end %>
          </div>
        <% end %>
    </div>
    <% end %>
  </div>

  <div class="col col-md-6">
    <% if @owned_ships.size > 0 %>
      <div class="dashboard_card armada d-flex flex-column">
        <div class="header owned">Mi Armada</div>
        <% if @owned_ships.empty? %>
          <div class="ship_text d-flex flex-column m-2 ml-3">
            You own no ships, matey. Better start looking for treasure maps.
          </div>
        <% else %>
          <% @owned_ships.each do |ship| %>
            <div class="ship_card">
              <div class="ship_text d-flex flex-column m-2 ml-3">
                <%= link_to ship.name, pirate_ship_path(ship) %>
              </div>
              <% unless ship == @owned_ships.last %>
                <hr>
              <% end %>
            </div>
          <% end %>
        <% end %>
        <div id="map"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    <% end %>

  </div>

app/views/pages/home.html.erb
<div class="my-banner">
  <div class="overlay"></div>

  <div class="home-page">
    <%= link_to pirate_ships_path, class: 'text-homepage', style: 'text-decoration: none; color: white;' do %>
      <h1>Tortuga Bay</h1>
      <h2>The parrfect ship <br>for all yer treasure hunting needs.</h2>
    <% end %>

    <div class= "search">
      <%= form_tag pirate_ships_path , method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "search-field",
          placeholder: "Choose your port?"
        %>
        <%= button_tag(type: "submit", class: "search-button") do %>
            <i class="fas fa-search"></i>
        <% end %>
      <% end %>
    </div>

  </div>

  </div>

app/views/pages/map.html.erb
 <div id="map"
     style="width: 100%; height: 830px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/pirate_ships/_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
      <h3>Pirate ship:</h3>
      <%= simple_form_for [@pirate_ship] do |f| %>
          <%= f.input :name, placeholder: 'Enter the name of your ship' %>
          <%= f.input :ship_type, placeholder: 'Enter the type of your ship' %>
          <%= f.input :description, placeholder: 'Enter a description about the ship' %>
          <%= f.input :port, placeholder: 'Enter the name of the port your ship is harbored in' %>
          <%=f.input :capacity, as: :numeric %>
          <%=f.input :number_of_canons, as: :numeric %>
          <%=f.input :parrot_friendlyness, as: :numeric %>
          <%=f.input :pictures, as: :file, input_html: { multiple: true } %>
          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pirate_ships/_info_window.html.erb
<div class="ship-card-image" style="background-image: url('<%= cl_image_path pirate_ship.pictures.first.key %>')"></div>
<h2><%= pirate_ship.name %></h2>
<h4>Port:  <%= pirate_ship.port %></h4>
<%= button_to 'See Ship', pirate_ship_path(pirate_ship), class: "btn btn-success" %>

app/views/pirate_ships/edit.html.erb
<%= render 'form' %>

app/views/pirate_ships/index.html.erb
<div class="ships_container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>Pirate Ships</h1>
    </div>
  </div>

  <div class="row">
    <% @pirate_ships.each do |pirate_ship| %>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="ship-card">
          <div class="ship-card-image" style="background-image: url('<%= cl_image_path pirate_ship.pictures.first.key %>')"></div>
          <div class="ship-card-content">
            <div class="ship-card-title">
              <h2><%= pirate_ship.name %></h2>
            </div>
            <p><%= pirate_ship.description %></p>
          </div>
          <div class="ship-card-actions">
            <div class='see-button'><%= link_to 'See Ship', pirate_ship_path(pirate_ship) %></div>
            <% if current_user == pirate_ship.user %>
            <div class='edit-button'><%= link_to 'Edit Ship', edit_pirate_ship_path(pirate_ship) %></div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pirate_ships/new.html.erb
<%= render 'form' %>

app/views/pirate_ships/show.html.erb
<div class="pirate_ship_show_container">

  <div class='ship-intro'>
    <div class='name'>
      <h1><b><%= @pirate_ship.name%><b></h1>
      <h4><%= @pirate_ship.description%></h4>
    </div>
    <% @pirate_ship.pictures.each do |picture| %>
      <%= cl_image_tag picture.key, alt: @pirate_ship.name, :class => "ship-page-image"%>
    <% end %>

    <div>
      <ul class='ship-details'>
        <li><i class="fa fa-solid fa-anchor"></i>Port: <%= @pirate_ship.port.split(", ")[0]%></li>
        <li><i class="fa-solid fa-ship"></i>Type: <%= @pirate_ship.ship_type%></li>
        <li><i class="fa fa-solid fa-users"></i>Capacity: <%= @pirate_ship.capacity%></li>
        <li><i class="fa-solid fa-bowling-ball"></i> Number of cannons: <%= @pirate_ship.number_of_canons%></li>
        <li><i class="fa-solid fa-crow"></i>Parrot friendlyness: <%= @pirate_ship.parrot_friendlyness%></li>
        <li><i class="fa-solid fa-map-location"></i>Country: <%= @pirate_ship.port.split(", ")[1]%></li>
      </ul>
    </div>
        <div>
      <% booker = @pirate_ship.bookings.any? {|booking| booking.user == current_user}%>
      <% booker_booking = @pirate_ship.bookings.find {|booking| booking.user == current_user}%>
  
      <% if booker %>
        <div class='book-button'><%=link_to "Book again", new_pirate_ship_booking_path(@pirate_ship)%></div>
        <div class='book-button'><%=link_to "Check your booking", pirate_ship_booking_path(@pirate_ship, booker_booking.id)%></div>
      <%else%>
        <% if current_user != @pirate_ship.user %>
          <div class='book-button'><%=link_to "Book now", new_pirate_ship_booking_path(@pirate_ship)%></div>
        <%else%>
          <div class='book-button'><%=link_to "Edit", edit_pirate_ship_path(@pirate_ship)%></div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class='map-and-banner'>
    <div id="map"
          style="width:95%; height: 530px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
    <div class='owner-banner'>
     <h2>Owner: <%=@pirate_ship.user.name%>   <%=image_tag @pirate_ship.user.avatar_url, alt:@pirate_ship.user.name, class: 'avatar-larger'%></h2>
    </div>
  </div>
  
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-white">
  <%= link_to '/', style: 'text-decoration: none; color: black;' do %>
    <div class="brand">
      <%= image_tag 'tortugabay.png', class: 'logo' %>
      <p>Tortuga Bay</p>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <div class="navbar-links">
      <ul>
        <li>
          <%= link_to "All Ships", "/pirate_ships", class: "navbar-link" %>
        </li>
        <li>
          <%= link_to "Map", "/map", class: "navbar-link" %>
        </li>
        <li>
          <div class="dropdown">
            <a type= "button" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <%= image_tag (current_user.avatar_url || 'pirate_skull.jpg'), class: "avatar" %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "All Ships", "/pirate_ships", class: "dropdown-item navbar-hide"%>
              <%= link_to "Map", "/map", class: "dropdown-item navbar-hide border-bottom" %>
              <%= link_to "Dashboard", "/dashboard", class: "dropdown-item" %>
              <%= link_to "Edit profile", "#", class: "dropdown-item" %>
              <%= link_to "Create ship", "/pirate_ships/new", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="navbar-links">
      <li>
        <%= link_to "Login", new_user_session_path%>
      </li>
    </div>
  <% end %>
</div>